vegaprotocol/vegacapsule

net_confs/config_checkpoint.hcl, net_confs/config_example.hcl, net_confs/config_nullchain.hcl, net_confs/config_snapshot.hcl, net_confs/node_set_templates/default/vega_full.tmpl, net_confs/node_set_templates/default/vega_validators.tmpl, net_confs/node_set_templates/default/vega_validators_clef.tmpl, net_confs/node_set_templates/sentry/vega_full.tmpl, net_confs/node_set_templates/sentry/vega_sentry.tmpl, net_confs/node_set_templates/sentry/vega_validators.tmpl, net_confs/stagnet_config.hcl
Some vega configuration fields have been renamed or removed.
=> fix: vega config removed field + renamed

CHANGELOG.md, go.mod, go.sum, net_confs/config_checkpoint.hcl, net_confs/config_example.hcl, net_confs/config_nullchain.hcl, net_confs/config_snapshot.hcl, net_confs/node_set_templates/default/vega_full.tmpl, net_confs/node_set_templates/default/vega_validators.tmpl, net_confs/node_set_templates/default/vega_validators_clef.tmpl, net_confs/node_set_templates/sentry/vega_full.tmpl, net_confs/node_set_templates/sentry/vega_sentry.tmpl, net_confs/node_set_templates/sentry/vega_validators.tmpl, net_confs/stagnet_config.hcl
Changes required to support the following core PR: https://github.com/vegaprotocol/vega/pull/5530
close #188
=> fix: move the ethereum rpc address configuration

CHANGELOG.md, cmd/ethereum.go, config/config.go, ethereum/commands.go, ethereum/keystore.go, ethereum/smartcontracts.go, generator/vega/clef.go, generator/vega/commands.go, generator/vega/generator.go, jobs/clef.tmpl, net_confs/config_clef.hcl, net_confs/node_set_templates/default/tendermint_full.tmpl
=> feat: fix multisig

net_confs/config_external_postgres.hcl, net_confs/node_set_templates/default/data_node_full.tmpl, net_confs/node_set_templates/default/data_node_full_external_postgres.tmpl
All of the configurations use the embedded PostgreSQL by default. 
There is a separate config to use external PostgreSQL started in the docker.
=> feat: Update configuration to use SQLStorage

Jenkinsfile
=> ci: add Jenkinsfile to run system-tests

CHANGELOG.md, net_confs/config_checkpoint.hcl, net_confs/config_example.hcl, net_confs/config_snapshot.hcl, net_confs/genesis.tmpl
=> Removed old network param

CHANGELOG.md, cmd/network_bootstrap.go, cmd/network_generate.go, cmd/network_start.go, cmd/network_stop.go, cmd/nodes_add.go, cmd/nodes_start.go, cmd/nodes_stop.go, cmd/nomad.go, cmd/nomad_log.go, cmd/template_nomad.go, config/config.go, go.mod, go.sum, nomad/client.go, nomad/client_allocs.go, nomad/job_runner.go, nomad/job_runner_defaults.go, utils/utils.go
=> feat: Improve failure detection and logging

CHANGELOG.md, generator/wallet/commands.go
=> Remove version check from wallet commands that doesn't support it anymore

CHANGELOG.md, nomad/client.go, nomad/client_allocs.go
=> Fix Nomad timeout issues

CHANGELOG.md, cmd/nomad_log.go, logscollector/logs_collector.go, nomad/job_runner_defaults.go
=> feat: improve logs collection

CHANGELOG.md, nomad/client.go, nomad/client_errors.go, nomad/job_runner_defaults.go
=> Disable Nomad allocations/tasks restarts

CHANGELOG.md, config/config.go, net_confs/config.hcl, nomad/job_runner_defaults.go
part of https://github.com/vegaprotocol/vega/issues/6020
=> feat: allow to specify resources for docker tasks

CHANGELOG.md, cmd/logs.go, cmd/network_bootstrap.go, cmd/network_start.go, cmd/nomad.go, cmd/nomad_log.go, cmd/nomad_log_tail.go, cmd/root.go, logscollector/collector.go, logscollector/printer.go, nomad/client.go, nomad/client_errors.go, nomad/job_runner.go, nomad/job_runner_defaults.go, readme.md, types/consts.go
=> feat: add functionality to print job logs on time out

generator/vega/commands.go
Network with clef starting!: https://jenkins.ops.vega.xyz/blue/organizations/jenkins/common%2Fsystem-tests-wrapper/detail/system-tests-wrapper/14116/pipeline/224
=> fix: swap arg order

CHANGELOG.md, generator/generator.go, net_confs/node_set_templates/default/visor_run.tmpl
=> fix remove Visor node

CHANGELOG.md, cmd/nodes_add.go, cmd/nodes_start.go
=> Add multiple nodes at the same time

.github/workflows/project_managment.yml
To fix:
gh: The `ProjectNext` API is deprecated in favour of the more capable `ProjectV2` API. Follow the ProjectV2 guide at https://github.blog/changelog/2022-06-23-the-new-github-issues-june-23rd-update/, to find a suitable replacement.
Error: Process completed with exit code 1.
=> fix: update project manage action

CHANGELOG.md, nomad/client.go, nomad/job_runner.go
=> fix: do no start jobs that already runs

net_confs/node_set_templates/default/data_node_full_external_postgres.tmpl, net_confs/node_set_templates/default/data_node_full_snapshosts.tmpl
closes #334  .
After fix network looks green:
=> feat: fix missing port in the data-node de history config

CHANGELOG.md, net_confs/config.hcl, net_confs/node_set_templates/default/data_node_full.tmpl, net_confs/node_set_templates/default/data_node_full_external_postgres.tmpl, net_confs/node_set_templates/default/data_node_full_snapshosts.tmpl, net_confs/node_set_templates/default/tendermint_full.tmpl, net_confs/node_set_templates/default/tendermint_validators.tmpl, net_confs/node_set_templates/default/vega_full.tmpl, net_confs/node_set_templates/default/vega_full_visor.tmpl, net_confs/node_set_templates/default/vega_full_visor_snap.tmpl, net_confs/node_set_templates/default/vega_validators.tmpl, net_confs/node_set_templates/default/vega_validators_clef.tmpl, nomad/job_runner_defaults.go, nomad/runner/config.go
Update the config files to allow us to support more that 9 nodes in a network.
Closes #337
=> Support more than 9 nodes

.gitignore, cmd/template_node_sets.go, generator/datanode/generator.go, generator/datanode/templates.go, generator/generator.go, go.mod, go.sum, net_confs/node_set_templates/default/data_node_full_external_postgres.tmpl, net_confs/node_set_templates/default/data_node_full_snapshosts.tmpl
=> fix: remove hardcoded bootstrap peers

CHANGELOG.md, generator/datanode/templates.go, net_confs/node_set_templates/default/data_node_full_external_postgres.tmpl, net_confs/node_set_templates/default/data_node_full_snapshosts.tmpl
=> fix: templating data node IPSF peers

net_confs/config.hcl, net_confs/config_checkpoint.hcl, net_confs/config_clef.hcl, net_confs/config_data_node_snapshot.hcl, net_confs/config_example.hcl, net_confs/config_external_postgres.hcl, net_confs/config_frontends.hcl, net_confs/config_nullchain.hcl, net_confs/config_sentry_datanode.hcl, net_confs/config_snapshot.hcl, net_confs/config_visor_mixed.hcl, net_confs/config_visor_only.hcl, net_confs/stagnet_config.hcl
=> fix: Ethereum use ws instead of http

CHANGELOG.md, generator/wallet/commands.go, generator/wallet/generator.go, types/types.go
=> Do not parse wallet initialisation output anymore 

CHANGELOG.md, nomad/job_runner.go
=> fix: stopped failed jobs

CHANGELOG.md, generator/datanode/generator.go, net_confs/config.hcl, net_confs/node_set_templates/default/data_node_full_external_postgres.tmpl, net_confs/node_set_templates/default/data_node_full_snapshosts.tmpl, types/types.go
=> feat: add swarm key to data node

.github/workflows/start-stop-network-test-configs.yml, cmd/install_dependencies.go, net_confs/config_frontends.hcl, net_confs/node_set_templates/default/data_node_full_external_postgres.tmpl, net_confs/node_set_templates/default/tendermint_full.tmpl, net_confs/node_set_templates/default/vega_full.tmpl, net_confs/node_set_templates/default/visor_config.tmpl, net_confs/node_set_templates/default/visor_run.tmpl, readme.md
=> chore: update readme, latest version and templates

nomad/client_allocs.go
=> fix: typo fix in output

CHANGELOG.md, config/exec_config.go, config/network_config.go, nomad/job_runner.go, nomad/job_runner_defaults.go
closes #365 
close vegaprotocol/system-tests#1528
=> feat: add exec prestart

go.mod, go.sum, net_confs/config_checkpoint.hcl, net_confs/config_example.hcl, net_confs/config_snapshot.hcl, net_confs/genesis.tmpl
This is (about to be) renamed in core and needs corresponding changes here
=> chore: rename stakeToCcySiskas stakeToCcyVolume

generator/datanode/templates.go, net_confs/node_set_templates/default/data_node_full.tmpl, net_confs/node_set_templates/default/data_node_full_external_postgres.tmpl, net_confs/node_set_templates/default/data_node_full_external_postgres_visor.tmpl, net_confs/node_set_templates/default/data_node_full_snapshosts.tmpl
closes: https://github.com/vegaprotocol/devops-infra/issues/1679
=> feat: migrate to networkhistory from dehistory

go.mod, go.sum
Related PRs:
- https://github.com/vegaprotocol/vega/pull/8144
- https://github.com/vegaprotocol/system-tests/pull/2068
- https://github.com/vegaprotocol/vegacapsule/pull/390
=> feat: update vega version

CHANGELOG.md, nomad/runner/binary_installer.go
=> feat: create install path if not exists

ethereum/multisig.go, install_vega_bins.md
=> fix: typos
